In [3]:
import numpy as np

#### Data Centering 

In [17]:
data = np.array([10,20,30,40,50])

In [7]:
mean = data.mean()

In [9]:
mean

np.float64(30.0)

In [11]:
centered_data = data - mean

In [13]:
centered_data

array([-20., -10.,   0.,  10.,  20.])

#### Data Standardization

In [20]:
std_dev = np.std(data)

In [24]:
standardized_data = (data - mean)/std_dev

In [26]:
standardized_data

array([-1.41421356, -0.70710678,  0.        ,  0.70710678,  1.41421356])

#### Log Transformation

In [29]:
log_transformed_data = np.log(data)

In [31]:
log_transformed_data

array([2.30258509, 2.99573227, 3.40119738, 3.68887945, 3.91202301])

In [33]:
print("Centred Data",centered_data)
print("Standardized Data",standardized_data)
print("Log Transformed Data",log_transformed_data)

Centred Data [-20. -10.   0.  10.  20.]
Standardized Data [-1.41421356 -0.70710678  0.          0.70710678  1.41421356]
Log Transformed Data [2.30258509 2.99573227 3.40119738 3.68887945 3.91202301]
